modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See download page for lists of versions.
license="MIT"

#clientSideOnly=true #optional - defaults to false if absent

[[mixins]]
config="fisch.mixins.json"


[[mods]] #mandatory
modId="fisch" #mandatory
version="0.1" #mandatory
displayName="FischForge" #mandatory
authors="kuko" #optional
description='''Example mod description.\nNewline characters can be used and will be replaced properly.'''

[[dependencies.fisch]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.fisch]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

